/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#696360",
        "primary": "#ffffff",
        "on-primary-fixed-variant": "#454747",
        "on-secondary-fixed": "#1a1c1c",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "surface-container-low": "#1c1b1b",
        "secondary": "#c6c6c6",
        "on-primary-fixed": "#1a1c1c",
        "surface-container": "#201f1f",
        "glass-surface": "rgba(10, 10, 10, 0.7)",
        "inverse-primary": "#5d5f5f",
        "secondary-fixed-dim": "#c6c6c6",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "on-primary": "#2f3131",
        "tertiary": "#ffffff",
        "surface-container-highest": "#353534",
        "silver-gray": "#B8B8B8",
        "background": "#131313",
        "charcoal": "#111111",
        "tertiary-container": "#e9e1dd",
        "secondary-fixed": "#e3e2e2",
        "surface": "#131313",
        "outline": "#8e9192",
        "tertiary-fixed-dim": "#cdc5c1",
        "tertiary-fixed": "#e9e1dd",
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed-variant": "#4b4643",
        "primary-fixed-dim": "#c6c6c7",
        "on-error": "#690005",
        "on-primary-container": "#636565",
        "primary-fixed": "#e2e2e2",
        "matte-black": "#0A0A0A",
        "error-container": "#93000a",
        "on-secondary-container": "#b8b8b8",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#1e1b19",
        "error": "#ffb4ab",
        "surface-tint": "#c6c6c7",
        "secondary-container": "#484949",
        "primary-container": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "on-secondary-fixed-variant": "#464747",
        "on-secondary": "#2f3131",
        "outline-variant": "#444748",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#34302d",
        "on-surface-variant": "#c4c7c8"
      },
      spacing: {
        "stack-md": "16px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "edge-margin-mobile": "20px",
        "gutter": "24px",
        "edge-margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }]
      },
      borderRadius: {
        '3xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
