"""Add foreign keys to network edges

Revision ID: 982b4134b6e3
Revises: 36e02c36c598
Create Date: 2026-06-25 19:52:45.534176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982b4134b6e3'
down_revision: Union[str, None] = '36e02c36c598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
